[package]
name = "fortify_derive"
version = "0.1.0"
edition = "2021"

[lib]
name = "fortify_derive"
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["full"] }